steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/keerthanacicd/hello-world-dag-image:v1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/keerthanacicd/hello-world-dag-image:v1']
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install apache-airflow && python -m unittest tests/test_hello_world_dag.py'

images:
  - 'gcr.io/keerthanacicd/hello-world-dag-image:v1'