steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/Keerthanacicd/hello-world-dag-image', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/Keerthanacicd/hello-world-dag-image']
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install apache-airflow && python -m unittest tests/test_hello_world_dag.py'

images:
  - 'gcr.io/Keerthanacicd/hello-world-dag-image'